openapi: 3.0.1
info:
  title: StromGedacht API
  termsOfService: https://www.stromgedacht.de/api-info/nutzungsbedingungen
  contact:
    url: https://www.stromgedacht.de
    email: stromgedacht@transnetbw.de
  version: v1
paths:
  /v1/forecast:
    get:
      tags:
        - RegionForecast
      summary: Returns requested forecast values for provided zip
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: from
          in: query
          description: Data will be returned from this datetime on | This field is optional. By providing no date it uses the date 7 days ago | Only up to 7 days into the past can be requested
          style: form
          schema:
            type: string
            format: date-time
          example: '2023-09-12'
        - name: to
          in: query
          description: Data will be returned to this datetime | This field is optional. By providing no date it uses the date 1 day in the future | Only up to 1 day into the future can be requested
          style: form
          schema:
            type: string
            format: date-time
          example: '2023-09-18'
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastViewModel'
        '400':
          description: Missing query data or wrong date format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /v1/now:
    get:
      tags:
        - RegionStates
      summary: Returns current RegionState
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionStateNowViewModel'
        '400':
          description: Missing query data or wrong date format
  /v1/states:
    get:
      tags:
        - RegionStates
      summary: Returns requested region states by provided dates
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: from
          in: query
          description: Data will be returned from this datetime on | Only up to 4 days into the past can be requested
          required: true
          style: form
          schema:
            type: string
            format: date-time
          example: '2024-04-09T00:00:00+02:00'
        - name: to
          in: query
          description: Data will be returned to this datetime | Only up to 2 days into the future can be requested
          required: true
          style: form
          schema:
            type: string
            format: date-time
          example: '2024-04-15T23:59:59+02:00'
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionStateRangeViewModel'
        '400':
          description: Missing query data or wrong date format
  /v1/statesRelative:
    get:
      tags:
        - RegionStates
      summary: Returns requested region states by provided hours
      parameters:
        - name: zip
          in: query
          description: The zip code of the region where the data will be used
          required: true
          style: form
          schema:
            type: string
        - name: hoursInFuture
          in: query
          description: Data will be returned to the provided amount of hours in future | Only up to 2 days into the future can be requested
          required: true
          style: form
          schema:
            type: integer
            format: int32
        - name: hoursInPast
          in: query
          description: Data will be returned from the provided amount of hours in past | This field is optional | Only up to 4 days into the past can be requested
          style: form
          schema:
            type: integer
            format: int32
            default: 0
        - name: X-B2B-ID
          in: header
          description: Identifier of the business partner (B2B-ID) (Optional)
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegionStateRangeViewModel'
        '400':
          description: Missing query data or wrong date format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    ForecastPointInTimeViewModel:
      required:
        -  dateTime
        -  value
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
        value:
          type: number
          format: double
      additionalProperties: false
    ForecastViewModel:
      required:
        - load
        - renewableEnergy
        - residualLoad
        - superGreenThreshold
      type: object
      properties:
        load:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
        renewableEnergy:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
        residualLoad:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
        superGreenThreshold:
          type: array
          items:
            $ref: '#/components/schemas/ForecastPointInTimeViewModel'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
      additionalProperties: { }
    RegionState:
      enum:
        - 1
        - 2
        - 3
        - 4
        - -1
      x-enum-varnames:
        - Green
        - Yellow
        - Orange
        - Red
        - SuperGreen
      type: integer
      format: int32
      description: "<p>Possible values:</p>\n<ul>\n<li><b>1</b> = green</li>\n<li><b>2</b> = yellow</li>\n<li><b>3</b> = orange</li>\n<li><b>4</b> = red</li>\n<li><b>-1</b> = superGreen</li>\n</ul>\n"
    RegionStateNowViewModel:
      required:
        -  state
      type: object
      properties:
        state:
          $ref: '#/components/schemas/RegionState'
      additionalProperties: false
    RegionStateRangeViewModel:
      required:
        -  states
      type: object
      properties:
        states:
          type: array
          items:
            $ref: '#/components/schemas/RegionStateViewModel'
      additionalProperties: false
    RegionStateViewModel:
      required:
        -  from
        -  to
        -  state
      type: object
      properties:
        from:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
        state:
          $ref: '#/components/schemas/RegionState'
      additionalProperties: false