// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20230506011706-29ebe3262399 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for RegionState.
const (
	Green  RegionState = 1
	Orange RegionState = 3
	Red    RegionState = 4
	Yellow RegionState = 2
)

// RegionState Possible values:
//
//	1 = green (normal operation - you do not need to do anything else)
//	2 = yellow (bring consumption forward - use electricity now)
//	3 = orange (reduce consumption to save costs and CO2)
//	4 = red (reduce consumption to prevent power shortage)
type RegionState int32

// RegionStateNowViewModel defines model for RegionStateNowViewModel.
type RegionStateNowViewModel struct {
	// State Possible values:
	//   1 = green (normal operation - you do not need to do anything else)
	//   2 = yellow (bring consumption forward - use electricity now)
	//   3 = orange (reduce consumption to save costs and CO2)
	//   4 = red (reduce consumption to prevent power shortage)
	State RegionState `json:"state"`
}

// RegionStateRangeViewModel defines model for RegionStateRangeViewModel.
type RegionStateRangeViewModel struct {
	States []RegionStateViewModel `json:"states"`
}

// RegionStateViewModel defines model for RegionStateViewModel.
type RegionStateViewModel struct {
	From time.Time `json:"from"`

	// State Possible values:
	//   1 = green (normal operation - you do not need to do anything else)
	//   2 = yellow (bring consumption forward - use electricity now)
	//   3 = orange (reduce consumption to save costs and CO2)
	//   4 = red (reduce consumption to prevent power shortage)
	State RegionState `json:"state"`
	To    time.Time   `json:"to"`
}

// FromDateTime defines model for FromDateTime.
type FromDateTime = time.Time

// ToDateTime defines model for ToDateTime.
type ToDateTime = time.Time

// ZipCode defines model for ZipCode.
type ZipCode = string

// GetNowParams defines parameters for GetNow.
type GetNowParams struct {
	// Zip The zip code of the region where the data will be used
	Zip ZipCode `form:"zip" json:"zip"`
}

// GetStatesParams defines parameters for GetStates.
type GetStatesParams struct {
	// Zip The zip code of the region where the data will be used
	Zip ZipCode `form:"zip" json:"zip"`

	// From Data will be returned from this datetime on.
	// Only up to 4 days into the past can be requested
	From FromDateTime `form:"from" json:"from"`

	// To Data will be returned to this datetime
	// Only up to 2 days into the future can be requested
	To ToDateTime `form:"to" json:"to"`
}
